language: python
python:
  - "3.8"
install:
  # Attempt to work around Home Assistant not being declared through PEP 561
  # Details: https://github.com/home-assistant/core/pull/28866#pullrequestreview-319309922
  - curl -LsSf --retry 5 -o ~/homeassistant-core.zip https://github.com/home-assistant/core/archive/master.zip
  - unzip -q ~/homeassistant-core.zip -d ~/homeassistant
  - pip install -r ~/homeassistant/core-master/requirements_test.txt

  - make install-dev
script:
  - make --keep-going lint
